### PR TITLE
Update TWC to 2.9.4

### PR DESCRIPTION
**Pull request by YakovL**
The updated is made based on this [example](https://github.com/simonbaird/tiddlyhost/commit/753a7beed663798fe9e5fd266f1a5070bb5b4a16). Also contains more accurate description of TWC.

### CODE REVIEW

**Comment by simonbaird** [comment]
Awesome, thanks very much.

**Comment by simonbaird** [comment]
I tested it locally and it seems like the new TW Classic empty works fine. Let's merge.

FYI the description and tooltip changes won't take effect right away. I might make a few tweaks to them and do an update later.

**Comment by YakovL** [comment]
Right, thanks Simon!

Are additional steps to update strings something like a ruby thing, or a localization issue?

**Comment by simonbaird** [comment]
> And a question for a future PR: to propose changes in ThostUploadPlugin. is it enough to modify [/rails/tw_content/plugins/thost_upload_plugin.js.erb](https://github.com/simonbaird/tiddlyhost/blob/1018a559a60d24701b4090d15d52933281b2cf86/rails/tw_content/plugins/thost_upload_plugin.js.erb)?

Correct.

**Comment by YakovL** [comment]
> That seeds file is used to populate a brand new empty database, so it's not going to affect the production database right away. There'll be a manual step needed which I will do next week some time.

Hey Simon, looks like the labels changes still didn't get to prod, could you take a look?

**Comment by simonbaird** [comment]
You're right - I didn't do that yet. Will take a look soon.

**Comment by simonbaird** [comment]
@YakovL FYI I updated the description and tooltip for TWC. It did tweak it a little from your version. Let me know if you don't like it. (See [here](https://github.com/simonbaird/tiddlyhost/commit/ababf98cbdb64e054d736b699098eb46b8b6b2a2#diff-82f41ad3d75ef5145073ddf0b12cd9aae8b683f1a6f9bb89f6796c86c07e816a).

**Comment by YakovL** [comment]
Thanks Simon, it's definitely better than before the PR anyway. It still sounds somewhat misleading as it shows "from before the 2012 "TiddlyWiki5" rewrite", but doesn't tell that it's actually live and evolving (until one opens the tooltip), so I'll think about another update. The current label sounds like TWC is an abandonware, which it is not

**Pull request merged**
